-- AlterTable
ALTER TABLE `advance_requests` MODIFY `docdate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `idcard` VARCHAR(200) NOT NULL,
    MODIFY `fromDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `toDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
