export const BASE_URL = 'http://192.168.1.201:8025'
// export const BASE_URL = "https://bharanipriya.pinnaclesystems.co.in"
export const PO_REGISTER = '/poRegister'
export const COMMON_MAST = '/commonMast'
export const SUPPLIER = '/supplier'
export const PO_DATA = '/poData'
export const MIS_DASHBOARD = '/misDashboard'
export const ORD_MANAGEMENT = '/ordManagement'
export const LOGIN_API = "users/login"
export const USERS_API = "users"
